modify workflow

diff --git a/.github/workflows/deploy-pages.yml b/.github/workflows/deploy-pages.yml
--- a/.github/workflows/deploy-pages.yml
+++ b/.github/workflows/deploy-pages.yml
@@ -1,73 +1,89 @@
-name: Deploy GitHub Pages
+# Sample workflow for building and deploying a Next.js site to GitHub Pages
+#
+# To get started with Next.js see: https://nextjs.org/docs/getting-started
+#
+name: Deploy Next.js site to Pages
 
 on:
+    # Runs on pushes targeting the default branch
     push:
-        branches: ["main"]
+        branches: [$default-branch]
 
+    # Allows you to run this workflow manually from the Actions tab
     workflow_dispatch:
 
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
     contents: read
     pages: write
     id-token: write
 
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
     group: "pages"
-    cancel-in-progress: true
+    cancel-in-progress: false
 
 jobs:
+    # Build job
     build:
-        environment:
-            name: github-pages
-            url: ${{ steps.deployment.outputs.page_url }}
-        runs-on: ubuntu-24.04
-
+        runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v4
 
-            - name: Setup Pages
-              uses: actions/configure-pages@v5
+            - name: Detect package manager
+              id: detect-package-manager
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                    echo "manager=yarn" >> $GITHUB_OUTPUT
+                    echo "command=install" >> $GITHUB_OUTPUT
+                    echo "runner=yarn" >> $GITHUB_OUTPUT
+                    exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                    echo "manager=npm" >> $GITHUB_OUTPUT
+                    echo "command=ci" >> $GITHUB_OUTPUT
+                    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                    exit 0
+                  else
+                    echo "Unable to determine package manager"
+                    exit 1
+                  fi
 
             - name: Setup Node
               uses: actions/setup-node@v4
               with:
-                  node-version: 20
+                  node-version: "20"
+                  cache: ${{ steps.detect-package-manager.outputs.manager }}
 
-            - name: Cache dependencies
-              uses: actions/cache@v4
-              id: node-modules_cache
-              env:
-                  cache-name: node-modules-cache
+            - name: Setup Pages
+              uses: actions/configure-pages@v5
               with:
-                  path: "**/node_modules"
-                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
-                  restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}
+                  static_site_generator: next
+
+            - name: Restore cache
+              uses: actions/cache@v4
+              with:
+                  path: |
+                      .next/cache
+
+                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+
+                  restore-keys: |
+                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
 
             - name: Install dependencies
-              if: ${{ steps.node-modules_cache.outputs.cache-hit != 'true' }}
-              run: npm install
+              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
-            - name: Cache Next
-              uses: actions/cache@v4
-              id: build_cache
-              env:
-                  cache-name: build-cache
-              with:
-                  path: "**/.next"
-                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**') }}
-                  restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}
-
-            - name: Build
-              run: npm run build
-              env:
-                  PUBLIC_URL: /web
+            - name: Build with Next.js
+              run: ${{ steps.detect-package-manager.outputs.runner }} next build
 
             - name: Upload artifact
               uses: actions/upload-pages-artifact@v3
               with:
-                  path: "./build"
+                  path: ./out
 
+    # Deployment job
     deploy:
         environment:
             name: github-pages
